### ISSUE TITLE
Github Action Error

### ISSUE THREAD

**Issue by Colin-XKL** [zentered/markdown-seo-check#80]
Logs when running this action:

```
Run zentered/markdown-seo-check@v1.1.5
  with:
    max_title_length: 70
    max_description_length: 150
    max_slug_length: 100
    includes: {*.md,*.mdx}
  env:
    GITHUB_TOKEN: ***
Starting Markdown SEO Check ...
Error: TypeError: Cannot read property 'number' of undefined
Error: Cannot read property 'number' of undefined
```

My github action config file
```yaml
name: SEO check

on:
  push:
    branches: [ master ]

jobs:
  seocheck:
    name: Markdown SEO Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Markdown SEO Check
        uses: zentered/markdown-seo-check@v1.1.5
        with:
          max_title_length: 70
          max_description_length: 150
          max_slug_length: 100
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Any idea about this error message?
